#!/usr/bin/env bash
# grub-quiet.sh — silence the GRUB menu on a kiosk node.
#
# Three things happen here:
#   1. drop a /etc/default/grub.d/ override that hides the menu,
#      kills the timeout, and zeroes GRUB_RECORDFAIL_TIMEOUT (the
#      30s "continue" prompt you see after a not-quite-clean boot)
#   2. clear the persistent `recordfail=1` flag in /boot/grub/grubenv
#      so the next boot doesn't keep showing the menu while the
#      override settles
#   3. update-grub
#
# Idempotent. Re-running just refreshes the override.

set -e

if [[ $EUID -ne 0 ]]; then
  echo "must run as root (use sudo)" >&2
  exit 1
fi

OVERRIDE=/etc/default/grub.d/99-sssds-quiet.cfg
mkdir -p /etc/default/grub.d
cat > "${OVERRIDE}" <<'EOF'
# Generated by SSSDS — keep kiosk boot fully silent.
GRUB_DEFAULT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=0
# 0 = no menu even after a failed boot, so a single bad shutdown can't
# leave the box sitting at a 30s prompt forever after.
GRUB_RECORDFAIL_TIMEOUT=0
GRUB_HIDDEN_TIMEOUT=0
GRUB_HIDDEN_TIMEOUT_QUIET=true
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
EOF
chmod 0644 "${OVERRIDE}"

# Clear any sticky recordfail flag from past reboots.
if command -v grub-editenv >/dev/null 2>&1; then
  grub-editenv /boot/grub/grubenv unset recordfail 2>/dev/null || true
fi

if command -v update-grub >/dev/null 2>&1; then
  update-grub
elif command -v grub-mkconfig >/dev/null 2>&1; then
  grub-mkconfig -o /boot/grub/grub.cfg
fi

echo "GRUB silenced — next boot should go straight to LXQt."
