#!/usr/bin/env bash
# provision-node.sh — turn a fresh Lubuntu install into a SSSDS client node.
#
# Usage:
#   sudo ./provision-node.sh ZONE NODE DASHBOARD_HOST AGENT_TOKEN
#
# Example:
#   sudo ./provision-node.sh 1 3 192.168.1.10:8080 abc123
#
# Idempotent: re-running with the same args updates identity and refreshes
# the install. Run from inside the cloned sssds/ repo.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "must run as root (use sudo)" >&2
  exit 1
fi

if [[ $# -ne 4 ]]; then
  cat >&2 <<EOF
usage: $0 ZONE NODE DASHBOARD_HOST AGENT_TOKEN
  ZONE             integer zone id (e.g. 1)
  NODE             integer node id within the zone (e.g. 3)
  DASHBOARD_HOST   host:port of the dashboard (e.g. 192.168.1.10:8080)
  AGENT_TOKEN      shared token from the dashboard's SSSDS_AGENT_TOKEN
EOF
  exit 2
fi

ZONE="$1"
NODE="$2"
DASHBOARD_HOST="$3"
AGENT_TOKEN="$4"

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
INSTALL_DIR="/opt/sssds"
CONFIG_DIR="/etc/sssds"
STATE_DIR="/var/lib/sssds"
LOG_DIR="/var/log/sssds"

echo "==> installing apt dependencies"
apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
  python3 python3-venv python3-pip \
  ethtool iproute2 \
  vlc python3-vlc \
  >/dev/null

echo "==> creating sssds user"
if ! id sssds >/dev/null 2>&1; then
  useradd --system --create-home --home-dir /home/sssds --shell /bin/bash sssds
fi
# Allow the user to talk to the X session so the VLC service can render.
usermod -aG video,audio sssds || true

echo "==> syncing files into ${INSTALL_DIR}"
mkdir -p "${INSTALL_DIR}" "${STATE_DIR}" "${LOG_DIR}"
# Use rsync if present, else cp. We exclude __pycache__ and the venv.
if command -v rsync >/dev/null; then
  rsync -a --delete \
    --exclude '__pycache__' --exclude '.venv' --exclude '.git' \
    "${REPO_DIR}/" "${INSTALL_DIR}/"
else
  cp -a "${REPO_DIR}/." "${INSTALL_DIR}/"
fi
chown -R sssds:sssds "${INSTALL_DIR}" "${STATE_DIR}" "${LOG_DIR}"

echo "==> creating Python venv"
sudo -u sssds python3 -m venv "${INSTALL_DIR}/.venv"
sudo -u sssds "${INSTALL_DIR}/.venv/bin/pip" install --quiet --upgrade pip
# Install both the agent and the VLC tool's deps into the same venv.
# pyobjc lines in VLC/requirements.txt are no-ops on Linux thanks to the
# sys_platform marker.
sudo -u sssds "${INSTALL_DIR}/.venv/bin/pip" install --quiet \
  -r "${INSTALL_DIR}/agent/requirements.txt" \
  -r "${INSTALL_DIR}/VLC/requirements.txt"

echo "==> writing identity to ${CONFIG_DIR}/identity.conf"
mkdir -p "${CONFIG_DIR}"
cat > "${CONFIG_DIR}/identity.conf" <<EOF
# Generated by provision-node.sh on $(date -Iseconds)
zone=${ZONE}
node=${NODE}
dashboard_url=ws://${DASHBOARD_HOST}/ws/agent
token=${AGENT_TOKEN}
EOF
chown root:sssds "${CONFIG_DIR}/identity.conf"
chmod 640 "${CONFIG_DIR}/identity.conf"

echo "==> installing sudoers rule"
install -m 0440 -o root -g root \
  "${INSTALL_DIR}/agent/sudoers.d.sssds" /etc/sudoers.d/sssds
visudo -c -q -f /etc/sudoers.d/sssds

echo "==> installing systemd units"
install -m 0644 "${INSTALL_DIR}/agent/systemd/sssds-agent.service" /etc/systemd/system/
install -m 0644 "${INSTALL_DIR}/agent/systemd/sssds-vlc.service"   /etc/systemd/system/
install -m 0644 "${INSTALL_DIR}/agent/systemd/sssds-wol.service"   /etc/systemd/system/
systemctl daemon-reload

echo "==> enabling services"
systemctl enable --now sssds-wol.service
systemctl enable --now sssds-agent.service
# NOTE: sssds-vlc.service is installed but NOT enabled here. The default
# VIDEO_PATH in vlc_timestamp_tool.py points at the dev machine — enable
# this service per-node only after you've placed the right video file
# and updated the path:
#     sudoedit /opt/sssds/VLC/vlc_timestamp_tool.py     # set VIDEO_PATH
#     sudo systemctl enable --now sssds-vlc.service

echo
echo "Done. Node identity: zone-${ZONE}-node-${NODE}"
echo "Tail the agent log with:"
echo "    journalctl -u sssds-agent -f"
echo
echo "Next: set VIDEO_PATH in /opt/sssds/VLC/vlc_timestamp_tool.py and run"
echo "    sudo systemctl enable --now sssds-vlc.service"
